# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, pypy2, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install flake8 pytest pytest-cov pydiff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 autopep8.py
        pycodestyle autopep8.py
    - name: doctest for readme
      if: matrix.python-version == 3.7
      run: |
        python -m doctest -v README.rst
    - name: Test with pytest
      run: |
        pytest --cov-report xml --cov=autopep8
        python test/acid.py -aaa --experimental test/example.py
        python test/acid.py -aaa --experimental test/example_with_reduce.py
        python test/acid.py --pycodestyle= -aaa --compare-bytecode --experimental test/example.py
        python test/acid.py --pycodestyle= --aggressive --line-range 550 610 test/inspect_example.py
        python test/acid.py --pycodestyle= --line-range 289 925 test/vectors_example.py
        python test/test_suite.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: matrix.python-version == 3.7 && success()
      with:
        fail_ci_if_error: true
